/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./views/**/*.{ejs,html,js}", "./public/**/*.{html,js,css}", "./src/**/*.{html,js,css}"],
  safelist: [
    // Common classes from your .ejs files:
    "bg-gray-50",
    "bg-gray-100",
    "container",
    "mx-auto",
    "px-4",
    "py-12",
    "text-center",
    "mb-12",
    "text-4xl",
    "font-bold",
    "mb-3",
    "text-xl",
    "text-gray-600",
    "bg-white",
    "rounded-lg",
    "shadow-md",
    "mt-5",
    "p-6",
    "text-2xl",
    "font-semibold",
    "mb-4",
    "text-gray-700",
    "text-blue-600",
    "hover:text-blue-800",
    "bg-gray-500",
    "hover:bg-gray-700",
    "py-2",
    "px-4",
    "rounded",
    "transition",
    "duration-200",
    "flex",
    "justify-between",
    "items-center",
    "block",
    "mb-1",
    "hover:text-blue-800",
    "bg-blue-500",
    "hover:bg-blue-700",
    "disabled:opacity-50",
    "mt-4",
    "mb-6",
    "border",
    "border-gray-300",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-blue-500",
    "bg-yellow-100",
    "border-l-4",
    "border-yellow-500",
    "p-4",
    "text-yellow-700",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
